[package]
version = "0.1.0"
name = "elgamal-script"
edition = "2021"

[dependencies]
sp1-sdk = { workspace = true, features = ["profiling"]}
elgamal-lib.workspace = true
rand = "0.8"

[build-dependencies]
sp1-build.workspace = true
